name: language-docker
version: '8.1.0'
synopsis: Dockerfile parser, pretty-printer and embedded DSL
description: 'All functions for parsing, printing and writting Dockerfiles are
  exported through @Language.Docker@. For more fine-grained operations look for
  specific modules that implement a certain functionality.

  See the <https://github.com/hadolint/language-docker GitHub project> for
  the source-code and examples.'
category: Development
author:
  - Lukas Martinelli
  - Pedro Tacla Yamada
  - José Lorenzo Rodríguez
maintainer:
  - lorenzo@seatgeek.com
copyright:
  - Lukas Martinelli, Copyright (c) 2016
  - Pedro Tacla Yamada, Copyright (c) 2016
  - José Lorenzo Rodríguez, Copyright (c) 2017
license: GPL-3
github: hadolint/language-docker
extra-source-files:
  - README.md

dependencies:
  - base >=4.13 && <5
  - bytestring >=0.10
  - megaparsec >=8.0
  - prettyprinter
  - split >=0.2
  - free
  - mtl
  - template-haskell
  - th-lift
  - text
  - time
  - containers
  - data-default-class

library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  - -fno-warn-unused-do-bind
  - -fno-warn-orphans
  exposed-modules:
  - Language.Docker
  - Language.Docker.Parser
  - Language.Docker.PrettyPrint
  - Language.Docker.Normalize
  - Language.Docker.Syntax
  - Language.Docker.Syntax.Lift
  - Language.Docker.EDSL
  - Language.Docker.EDSL.Quasi
  - Language.Docker.EDSL.Types

tests:
  hspec:
    main: Spec.hs
    source-dirs: test
    dependencies:
    - hspec
    - QuickCheck
    - language-docker
    - Glob
    - directory
    - filepath
    - process
    - HUnit >=1.2
    - megaparsec >=7.0
