# Runs on pull requests against master, and on master branch

name: Haskell Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches: [ master ]
    paths:
      - '.github/workflows/haskell.yml'
      - 'stack*.yaml'
      - 'hadolint.cabal'
      - 'src/**'
      - 'test/**'

jobs:
  hadolint:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
        - os: ubuntu-latest

    steps:

    # setup:

    - name: Check out
      uses: actions/checkout@v4


    - name: Setup Haskell
      id: setup-haskell-cabal
      uses: haskell-actions/setup@v2
      with:
          ghc-version: '9.8'

    # actions

    - name: Test
      run: cabal test --test-show-details=always
