# Runs on pull requests against master, and on master branch

name: Haskell Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches: [ master ]
    paths:
      - '.github/workflows/haskell.yml'
      - 'stack*.yaml'
      - 'hadolint.cabal'
      - 'src/**'
      - 'test/**'

jobs:
  hadolint:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
        - os: macos-latest
        - os: ubuntu-latest
        - os: windows-latest

    steps:

    # setup:

    - name: Check out
      uses: actions/checkout@v2


    - name: Setup Haskell
      id: setup-haskell-cabal
      uses: haskell/actions/setup@v1
      with:
          ghc-version: '8.10'
          enable-stack: true

    # actions

    - name: Test
      run: stack test
